[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@uniswap/v3-periphery/=lib/v3-periphery/',
    '@uniswap/v3-core/=lib/v3-core/',
    'foundry-devops=lib/foundry-devops',
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
